### ISSUE TITLE
[RunningHub_Omini_Fill]   ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by GuardSkill** [HM-RunningHub/ComfyUI_RH_OminiControl#9]
got prompt
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 108.55it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.26it/s]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 6887.20it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.75it/s]
  0%|                                                                                                                                               | 0/8 [00:00<?, ?it/s]Passing `txt_ids` 3d torch.Tensor is deprecated.Please remove the batch dimension and pass it as a 2d torch Tensor
Passing `img_ids` 3d torch.Tensor is deprecated.Please remove the batch dimension and pass it as a 2d torch Tensor
  0%|                                                                                                                                               | 0/8 [00:00<?, ?it/s]
!!! Exception during processing !!! not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/Disk1/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Disk1/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/custom_nodes/ComfyUI_RH_OminiControl/nodes.py", line 84, in run
    img = rof.run(ori_image, mask, prompt, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/custom_nodes/ComfyUI_RH_OminiControl/rh_omini_fill.py", line 88, in run
    result_latents = generate(
                     ^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/custom_nodes/ComfyUI_RH_OminiControl/src/generate.py", line 233, in generate
    noise_pred = tranformer_forward(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Disk1/ComfyUI/custom_nodes/ComfyUI_RH_OminiControl/src/transformer.py", line 139, in tranformer_forward
    image_rotary_emb = self.pos_embed(ids)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 65, in forward
    [rope(ids[..., i], self.axes_dim[i], self.theta) for i in range(n_axes)],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 65, in <listcomp>
    [rope(ids[..., i], self.axes_dim[i], self.theta) for i in range(n_axes)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Disk1/miniforge3/envs/comfyui311/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 44, in rope
    batch_size, seq_length = pos.shape
    ^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

Prompt executed in 15.34 seconds

**Comment by DragonQuix** [comment]
我也遇到同样错误。
I had the same error message.

**Comment by GuardSkill** [comment]
更新comfyui版本即可

DragonQuix ***@***.***> 于2024年12月26日周四 11:54写道：

**Comment by jacksonjack001** [comment]
same error，have update the comfyui to the latest version
